<?php
/*
 *   @Author: KnoxGuru <knoxguru@gmail.com>
 */
namespace KnoxGuru\Bundle\FreeRadiusSqlBundle\Lists;


class Attributes {

    public static function get() {
        return array( 
            "ARAP-Challenge-Response" =>        "ARAP-Challenge-Response",
            "ARAP-Features" =>  "ARAP-Features",
            "ARAP-Password" =>  "ARAP-Password",
            "ARAP-Security" =>  "ARAP-Security",
            "ARAP-Security-Data" =>     "ARAP-Security-Data",
            "ARAP-Zone-Access" =>       "ARAP-Zone-Access",
            "Access-Accept" =>  "Access-Accept",
            "Access-Challenge" =>       "Access-Challenge",
            "Access-Reject" =>  "Access-Reject",
            "Access-Request" =>         "Access-Request",
            "Accounting-Request" =>     "Accounting-Request",
            "Accounting-Response" =>    "Accounting-Response",
            "Acct-Authentic" =>         "Acct-Authentic",
            "Acct-Delay-Time" =>        "Acct-Delay-Time",
            "Acct-Input-Gigawords" =>   "Acct-Input-Gigawords",
            "Acct-Input-Octets" =>      "Acct-Input-Octets",
            "Acct-Input-Packets" =>     "Acct-Input-Packets",
            "Acct-Interim-Interval" =>  "Acct-Interim-Interval",
            "Acct-Link-Count" =>        "Acct-Link-Count",
            "Acct-Multi-Session-Id" =>  "Acct-Multi-Session-Id",
            "Acct-Output-Gigawords" =>  "Acct-Output-Gigawords",
            "Acct-Output-Octets" =>     "Acct-Output-Octets",
            "Acct-Output-Packets" =>    "Acct-Output-Packets",
            "Acct-Session-Id" =>        "Acct-Session-Id",
            "Acct-Session-Time" =>      "Acct-Session-Time",
            "Acct-Status-Type" =>       "Acct-Status-Type",
            "Acct-Terminate-Cause" =>   "Acct-Terminate-Cause",
            "Acct-Tunnel-Connection" =>         "Acct-Tunnel-Connection",
            "Acct-Tunnel-Packets-Lost" =>       "Acct-Tunnel-Packets-Lost",
            "CHAP-Challenge" =>         "CHAP-Challenge",
            "CHAP-Password" =>  "CHAP-Password",
            "Callback-Id" =>    "Callback-Id",
            "Callback-Number" =>        "Callback-Number",
            "Called-Station-Id" =>      "Called-Station-Id",
            "Calling-Station-Id" =>     "Calling-Station-Id",
            "Chargeable-User-Identity" =>       "Chargeable-User-Identity",
            "Class" =>  "Class",
	    "Cleartext-Password" => "Cleartext-Password",
            "Configuration-Token" =>    "Configuration-Token",
            "Connect-Info" =>   "Connect-Info",
            "DNS-Server-IPv6-Address" =>        "DNS-Server-IPv6-Address",
            "DS-Lite-Tunnel-Name" =>    "DS-Lite-Tunnel-Name",
            "Delegated-IPv6-Prefix" =>  "Delegated-IPv6-Prefix",
            "Delegated-IPv6-Prefix-Pool" =>     "Delegated-IPv6-Prefix-Pool",
            "EAP-Message" =>    "EAP-Message",
            "Error-Cause" =>    "Error-Cause",
            "Event-Timestamp" =>        "Event-Timestamp",
            "Extended-Type-1" =>        "Extended-Type-1",
            "Extended-Type-2" =>        "Extended-Type-2",
            "Extended-Type-3" =>        "Extended-Type-3",
            "Extended-Type-4" =>        "Extended-Type-4",
            "Extended-Vendor-Specific-1" =>     "Extended-Vendor-Specific-1",
            "Extended-Vendor-Specific-2" =>     "Extended-Vendor-Specific-2",
            "Extended-Vendor-Specific-3" =>     "Extended-Vendor-Specific-3",
            "Extended-Vendor-Specific-4" =>     "Extended-Vendor-Specific-4",
            "Extended-Vendor-Specific-5" =>     "Extended-Vendor-Specific-5",
            "Extended-Vendor-Specific-6" =>     "Extended-Vendor-Specific-6",
            "Filter-ID" =>      "Filter-ID",
            "Filter-Id" =>      "Filter-Id",
            "Framed-AppleTalk-Link" =>  "Framed-AppleTalk-Link",
            "Framed-AppleTalk-Network" =>       "Framed-AppleTalk-Network",
            "Framed-AppleTalk-Zone" =>  "Framed-AppleTalk-Zone",
            "Framed-Compression" =>     "Framed-Compression",
            "Framed-IP-Address" =>      "Framed-IP-Address",
            "Framed-IP-Netmask" =>      "Framed-IP-Netmask",
            "Framed-IPX-Network" =>     "Framed-IPX-Network",
            "Framed-IPv6-Address" =>    "Framed-IPv6-Address",
            "Framed-IPv6-Pool" =>       "Framed-IPv6-Pool",
            "Framed-IPv6-Prefix" =>     "Framed-IPv6-Prefix",
            "Framed-IPv6-Route" =>      "Framed-IPv6-Route",
            "Framed-Interface-Id" =>    "Framed-Interface-Id",
            "Framed-MTU" =>     "Framed-MTU",
            "Framed-Management-Protocol" =>     "Framed-Management-Protocol",
            "Framed-Pool" =>    "Framed-Pool",
            "Framed-Protocol" =>        "Framed-Protocol",
            "Framed-Route" =>   "Framed-Route",
            "Framed-Routing" =>         "Framed-Routing",
            "Idle-Timeout" =>   "Idle-Timeout",
            "Login-IP-Host" =>  "Login-IP-Host",
            "Login-IPv6-Host" =>        "Login-IPv6-Host",
            "Login-LAT-Group" =>        "Login-LAT-Group",
            "Login-LAT-Node" =>         "Login-LAT-Node",
            "Login-LAT-Port" =>         "Login-LAT-Port",
            "Login-LAT-Service" =>      "Login-LAT-Service",
            "Login-Service" =>  "Login-Service",
            "Login-TCP-Port" =>         "Login-TCP-Port",
            "Long-Extended-Type-1" =>   "Long-Extended-Type-1",
            "Long-Extended-Type-2" =>   "Long-Extended-Type-2",
            "MS-ARAP-Challenge" =>      "MS-ARAP-Challenge",
            "MS-ARAP-Password-Change-Reason" =>         "MS-ARAP-Password-Change-Reason",
            "MS-Acct-Auth-Type" =>      "MS-Acct-Auth-Type",
            "MS-Acct-EAP-Type" =>       "MS-Acct-EAP-Type",
            "MS-BAP-Usage" =>   "MS-BAP-Usage",
            "MS-CHAP-CPW-1" =>  "MS-CHAP-CPW-1",
            "MS-CHAP-CPW-2" =>  "MS-CHAP-CPW-2",
            "MS-CHAP-Challenge" =>      "MS-CHAP-Challenge",
            "MS-CHAP-Domain" =>         "MS-CHAP-Domain",
            "MS-CHAP-Error" =>  "MS-CHAP-Error",
            "MS-CHAP-LM-Enc-PW" =>      "MS-CHAP-LM-Enc-PW",
            "MS-CHAP-MPPE-Keys" =>      "MS-CHAP-MPPE-Keys",
            "MS-CHAP-NT-Enc-PW" =>      "MS-CHAP-NT-Enc-PW",
            "MS-CHAP-Response" =>       "MS-CHAP-Response",
            "MS-CHAP2-CPW" =>   "MS-CHAP2-CPW",
            "MS-CHAP2-Response" =>      "MS-CHAP2-Response",
            "MS-CHAP2-Success" =>       "MS-CHAP2-Success",
            "MS-Filter" =>      "MS-Filter",
            "MS-Link-Drop-Time-Limit" =>        "MS-Link-Drop-Time-Limit",
            "MS-Link-Utilization-Threshold" =>  "MS-Link-Utilization-Threshold",
            "MS-MPPE-Encryption-Policy" =>      "MS-MPPE-Encryption-Policy",
            "MS-MPPE-Encryption-Types" =>       "MS-MPPE-Encryption-Types",
            "MS-MPPE-Recv-Key" =>       "MS-MPPE-Recv-Key",
            "MS-MPPE-Send-Key" =>       "MS-MPPE-Send-Key",
            "MS-New-ARAP-Password" =>   "MS-New-ARAP-Password",
            "MS-Old-ARAP-Password" =>   "MS-Old-ARAP-Password",
            "MS-Primary-DNS-Server" =>  "MS-Primary-DNS-Server",
            "MS-Primary-NBNS-Server" =>         "MS-Primary-NBNS-Server",
            "MS-RAS-Vendor" =>  "MS-RAS-Vendor",
            "MS-RAS-Version" =>         "MS-RAS-Version",
            "MS-Secondary-DNS-Server" =>        "MS-Secondary-DNS-Server",
            "MS-Secondary-NBNS-Server" =>       "MS-Secondary-NBNS-Server",
            "Management-Policy-Id" =>   "Management-Policy-Id",
            "Management-Privilege-Level" =>     "Management-Privilege-Level",
            "Management-Transport-Protection" =>        "Management-Transport-Protection",
            "Message-Authenticator" =>  "Message-Authenticator",
            "Mobile-Node-Identifier" =>         "Mobile-Node-Identifier",
            "NAS-IP-Address" =>         "NAS-IP-Address",
            "NAS-IPv6-Address" =>       "NAS-IPv6-Address",
            "NAS-Identifier" =>         "NAS-Identifier",
            "NAS-Port" =>       "NAS-Port",
            "NAS-Port-Id" =>    "NAS-Port-Id",
            "NAS-Port-Type" =>  "NAS-Port-Type",
            "PKM-AUTH-Key" =>   "PKM-AUTH-Key",
            "PKM-CA-Cert" =>    "PKM-CA-Cert",
            "PKM-Config-Settings" =>    "PKM-Config-Settings",
            "PKM-Cryptosuite-List" =>   "PKM-Cryptosuite-List",
            "PKM-SA-Descriptor" =>      "PKM-SA-Descriptor",
            "PKM-SAID" =>       "PKM-SAID",
            "PKM-SS-Cert" =>    "PKM-SS-Cert",
            "Password-Retry" =>         "Password-Retry",
            "Port-Limit" =>     "Port-Limit",
            "Proxy-State" =>    "Proxy-State",
            "Reply-Message" =>  "Reply-Message",
            "Route-IPv6-Information" =>         "Route-IPv6-Information",
            "Service-Selection" =>      "Service-Selection",
            "Service-Type" =>   "Service-Type",
            "Session-Timeout" =>        "Session-Timeout",
            "State" =>  "State",
            "Stateful-IPv6-Address-Pool" =>     "Stateful-IPv6-Address-Pool",
            "Termination-Action" =>     "Termination-Action",
            "Tunnel-Assignment-ID" =>   "Tunnel-Assignment-ID",
            "Tunnel-Client-Auth-ID" =>  "Tunnel-Client-Auth-ID",
            "Tunnel-Client-Endpoint" =>         "Tunnel-Client-Endpoint",
            "Tunnel-Link-Reject" =>     "Tunnel-Link-Reject",
            "Tunnel-Link-Start" =>      "Tunnel-Link-Start",
            "Tunnel-Link-Stop" =>       "Tunnel-Link-Stop",
            "Tunnel-Medium-Type" =>     "Tunnel-Medium-Type",
            "Tunnel-Password" =>        "Tunnel-Password",
            "Tunnel-Preference" =>      "Tunnel-Preference",
            "Tunnel-Private-Group-ID" =>        "Tunnel-Private-Group-ID",
            "Tunnel-Reject" =>  "Tunnel-Reject",
            "Tunnel-Server-Auth-ID" =>  "Tunnel-Server-Auth-ID",
            "Tunnel-Server-Endpoint" =>         "Tunnel-Server-Endpoint",
            "Tunnel-Start" =>   "Tunnel-Start",
            "Tunnel-Stop" =>    "Tunnel-Stop",
            "Tunnel-Type" =>    "Tunnel-Type",
            "User-Name" =>      "User-Name",
            "User-Password" =>  "User-Password",
            "Vendor-Specific" =>        "Vendor-Specific",
	);
    }

    public static function getOpCheck() {
	return array(
		':=' => ':=', 
		'==' => '==', 
		'+=' => '+=', 
		'!=' => '!=', 
		'>'  => '>', 
		'<'  => '<', 
		'>=' => '>=', 
		'<=' => '<=', 
		'=~' =>'=~', 
		'!~' => '!~',
		'=*' => '=*',
		'!*' => '!*'
	);
    }

    public static function getOpReply() {
        return array(
                ':=' => ':=', 
                '+=' => '+=',
        );
    }
 

}



